### ISSUE TITLE
windows and linux problem with fsevents

### ISSUE THREAD

**Issue by timokd** [springboot-angular2-tutorial/angular2-app#3]
npm install doesn't work on a windows and also not on linux. It seems that fsevents is a dependency of webpack and fsevents only fits to Mac architecture.

this is a part of npm install --verbose 

...
npm info lifecycle angular2-tutorial@0.1.0~prepublish: angular2-tutorial@0.1.0
angular2-tutorial@0.1.0 c:\dev\_playground\angular2springboot\angular2-app
`-- extract-text-webpack-plugin@1.0.1  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.8
npm verb exit [ 0, true ]
npm info ok

Is ist possible to correct that so that the app also runs on windows or linux?

**Comment by akirasosa** [comment]
@timokd 
Thanks for reporting.

About windows, I will take a look. But it may take long time, because I have no windows...

About linux, it must work because TravisCI is success, which is run on [Ubuntu](https://travis-ci.org/springboot-angular2-tutorial/angular2-app#L14). Do you have any log about it?

**Comment by akirasosa** [comment]
@timokd 
> About linux, it must work because TravisCI is success

Ah sorry, there is no process to use ```watch``` in CI build. I will take a look into Linux case too.

**Comment by timokd** [comment]
@akirasosa 
This is the error message starting on Windows
C:\dev\_playground\angular2springboot\angular2-app>npm run server

> angular2-tutorial@0.1.0 server C:\dev\_playground\angular2springboot\angular2-app
> webpack-dev-server --inline --progress --profile --colors --display-error-details --display-cached --port 3001

 70% 2/2 build moduleshttp://localhost:3001/
webpack result is served from /__build__
content is served from C:\dev\_playground\angular2springboot\angular2-app
404s will fallback to /index.html
 46% 3/5 build modulests-loader: Using typescript@1.8.2 and C:\dev\_playground\angular2springboot\angular2-app\tsconfig.json
945ms build modules
6ms seal
11ms optimize
6ms hashing
22ms create chunk assets
2ms additional chunk assets
220ms optimize chunk assets
2ms optimize assets
9ms emit
Hash: cfba30c60b875490fcfa
Version: webpack 1.12.14
Time: 1235ms
     Asset       Size  Chunks             Chunk Names
    app.js  255 bytes       0  [emitted]  app
 vendor.js  254 bytes       1  [emitted]  vendor
 common.js     232 kB       2  [emitted]  common
   app.map   83 bytes       0  [emitted]  app
vendor.map   86 bytes       1  [emitted]  vendor
common.map     273 kB       2  [emitted]  common
chunk    {0} app.js, app.map (app) 40 bytes {2} [rendered]
    [0] multi app 40 bytes {0} [built] [1 error]
       factory:1ms building:1ms dependencies:73ms = 75ms
chunk    {1} vendor.js, vendor.map (vendor) 40 bytes {2} [rendered]
    [0] multi vendor 40 bytes {1} [built] [1 error]
       factory:1ms building:1ms = 2ms
chunk    {2} common.js, common.map (common) 211 kB [rendered]
    [1] (webpack)-dev-server/client?http://localhost:3001 2.67 kB {2} [built]
       [0] 2ms -> factory:76ms building:151ms = 229ms
    [2] ./~/url/url.js 22.3 kB {2} [built]
       [0] 2ms -> [1] 227ms -> factory:163ms building:46ms = 438ms
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [2] 209ms -> factory:19ms building:102ms = 559ms
    [4] (webpack)/buildin/module.js 251 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [2] 209ms -> [3] 121ms -> factory:206ms building:147ms = 912ms
    [5] ./~/querystring/index.js 127 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [2] 209ms -> factory:14ms building:6ms = 458ms
    [6] ./~/querystring/decode.js 2.4 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [2] 209ms -> [5] 20ms -> factory:64ms building:45ms = 567ms
    [7] ./~/querystring/encode.js 2.09 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [2] 209ms -> [5] 20ms -> factory:64ms building:46ms = 568ms
    [8] ./~/sockjs-client/lib/entry.js 244 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> factory:164ms building:56ms = 449ms
    [9] ./~/sockjs-client/lib/transport-list.js 613 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> factory:6ms building:7ms = 462ms
   [10] ./~/sockjs-client/lib/transport/websocket.js 2.68 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:60ms building:54ms dependencies:140ms = 716ms
   [11] ./~/process/browser.js 2.06 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:72ms building:206ms = 769ms
   [12] ./~/sockjs-client/lib/utils/event.js 2 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:39ms building:122ms dependencies:0ms = 652ms
   [13] ./~/sockjs-client/lib/utils/random.js 746 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:38ms building:115ms = 644ms
   [14] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [13] 153ms -> factory:94ms building:137ms = 875ms
   [15] ./~/sockjs-client/lib/utils/url.js 975 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:39ms building:126ms dependencies:60ms = 716ms
   [16] ./~/url-parse/index.js 6.55 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:70ms building:200ms = 761ms
   [17] ./~/requires-port/index.js 753 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [16] 270ms -> factory:153ms building:7ms = 921ms
   [18] ./~/url-parse/lolcation.js 1.4 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [16] 270ms -> factory:14ms building:141ms dependencies:1ms = 917ms
   [19] ./~/querystringify/index.js 1.3 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [16] 270ms -> factory:153ms building:16ms = 930ms
   [20] ./~/debug/browser.js 3.76 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:224ms building:65ms = 780ms
   [21] ./~/debug/debug.js 4.1 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [20] 289ms -> factory:130ms building:10ms = 920ms
   [22] ./~/ms/index.js 2.33 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [20] 289ms -> [21] 140ms -> factory:20ms building:3ms = 943ms
   [23] ./~/inherits/inherits_browser.js 672 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:220ms building:66ms = 777ms
   [24] ./~/sockjs-client/lib/event/emitter.js 1.11 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [10] 114ms -> factory:154ms building:72ms dependencies:1ms = 803ms
   [25] ./~/sockjs-client/lib/event/eventtarget.js 1.75 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:42ms building:134ms = 667ms
   [26] ./~/sockjs-client/lib/transport/browser/websocket.js 58 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [10] 114ms -> factory:194ms building:142ms = 912ms
   [27] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:61ms building:47ms dependencies:142ms = 712ms
   [28] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [27] 108ms -> factory:151ms building:64ms dependencies:3ms = 788ms
   [29] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [53] 154ms -> factory:120ms building:102ms dependencies:2ms = 840ms
   [30] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [53] 154ms -> [29] 222ms -> factory:75ms building:15ms dependencies:1ms = 929ms
   [31] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [53] 154ms -> [29] 222ms -> factory:75ms building:11ms dependencies:2ms = 926ms
   [32] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [27] 108ms -> factory:153ms building:68ms dependencies:113ms = 904ms
   [33] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [27] 108ms -> factory:158ms building:70ms dependencies:108ms = 906ms
   [34] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.67 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [27] 108ms -> [33] 228ms -> factory:117ms building:19ms dependencies:6ms = 940ms
   [35] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [27] 108ms -> factory:159ms building:75ms dependencies:111ms = 915ms
   [36] ./~/sockjs-client/lib/utils/browser.js 560 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:41ms building:131ms = 663ms
   [37] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:61ms building:61ms dependencies:140ms = 724ms
   [38] ./~/sockjs-client/lib/transport/sender/xdr.js 2.42 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [37] 122ms -> factory:148ms building:84ms dependencies:90ms = 906ms
   [39] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:61ms building:70ms dependencies:135ms = 728ms
   [40] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [39] 131ms -> factory:140ms building:74ms dependencies:98ms = 905ms
   [41] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [39] 131ms -> factory:141ms building:80ms = 814ms
   [42] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:62ms building:76ms dependencies:112ms = 712ms
   [43] ./~/sockjs-client/lib/transport/iframe.js 3.8 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [42] 138ms -> factory:135ms building:93ms dependencies:3ms = 831ms
   [44] ./~/sockjs-client/~/json3/lib/json3.js 43.3 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:246ms building:135ms dependencies:2ms = 874ms
   [45] (webpack)/buildin/amd-options.js 43 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [44] 381ms -> factory:43ms building:15ms = 930ms
   [46] ./~/sockjs-client/lib/version.js 25 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:44ms building:155ms = 690ms
   [47] ./~/sockjs-client/lib/utils/iframe.js 4.95 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [70] 202ms -> factory:49ms building:160ms dependencies:2ms = 904ms
   [48] ./~/sockjs-client/lib/utils/object.js 532 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:40ms building:132ms = 663ms
   [49] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:63ms building:79ms dependencies:125ms = 729ms
   [50] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.17 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [49] 142ms -> factory:131ms building:99ms dependencies:71ms = 905ms
   [51] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:63ms building:99ms dependencies:105ms = 729ms
   [52] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:64ms building:84ms dependencies:122ms = 732ms
   [53] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> factory:64ms building:90ms dependencies:96ms = 712ms
   [54] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.49 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [53] 154ms -> factory:120ms building:108ms dependencies:61ms = 905ms
   [55] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [9] 13ms -> [53] 154ms -> factory:121ms building:113ms dependencies:56ms = 906ms
   [56] ./~/sockjs-client/lib/main.js 11.9 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> factory:6ms building:36ms = 491ms
   [57] ./~/sockjs-client/lib/shims.js 18.2 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:35ms building:115ms = 641ms
   [58] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:38ms building:119ms dependencies:90ms = 738ms
   [59] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:40ms building:129ms dependencies:56ms = 716ms
   [60] ./~/sockjs-client/lib/utils/log.js 386 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:41ms building:132ms = 664ms
   [61] ./~/sockjs-client/lib/event/event.js 485 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:42ms building:132ms = 665ms
   [62] ./~/sockjs-client/lib/location.js 177 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:43ms building:134ms = 668ms
   [63] ./~/sockjs-client/lib/event/close.js 295 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:43ms building:140ms dependencies:41ms = 715ms
   [64] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:43ms building:136ms dependencies:45ms = 715ms
   [65] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:43ms building:145ms dependencies:53ms = 732ms
   [66] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [65] 188ms -> factory:59ms building:137ms dependencies:30ms = 905ms
   [67] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [65] 188ms -> factory:60ms building:149ms dependencies:3ms = 891ms
   [68] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [70] 202ms -> factory:49ms building:154ms dependencies:0ms = 896ms
   [69] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [65] 188ms -> factory:60ms building:153ms dependencies:1ms = 893ms
   [70] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> factory:44ms building:158ms dependencies:45ms = 738ms
   [71] ./~/sockjs-client/lib/facade.js 723 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [8] 220ms -> [56] 42ms -> [70] 202ms -> factory:48ms building:154ms dependencies:0ms = 895ms
   [72] ./~/strip-ansi/index.js 161 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> factory:161ms building:51ms = 441ms
   [73] ./~/ansi-regex/index.js 135 bytes {2} [built]
       [0] 2ms -> [1] 227ms -> [72] 212ms -> factory:12ms building:14ms = 467ms

ERROR in ./src/vendor.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\dev\_playground\angular2springboot\angular2-app\typings\main.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at C:\dev\_playground\angular2springboot\angular2-app\node_modules\ts-loader\index.js:193:22
    at Array.forEach (native)
    at ensureTypeScriptInstance (C:\dev\_playground\angular2springboot\angular2-app\node_modules\ts-loader\index.js:190:17)
    at Object.loader (C:\dev\_playground\angular2springboot\angular2-app\node_modules\ts-loader\index.js:375:14)
 @ multi vendor

ERROR in ./src/app/bootstrap.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (C:\dev\_playground\angular2springboot\angular2-app\node_modules\ts-loader\index.js:410:33)
 @ multi app
webpack: bundle is now VALID.

**Comment by akirasosa** [comment]
@timokd
> Module build failed: Error: ENOENT: no such file or directory, open 'C:\dev_playground\angular2springboot\angular2-app\typings\main.d.ts'

It looks same issue here. https://github.com/AngularClass/angular2-webpack-starter/issues/153#issuecomment-164440424

Could you try these commands?
```
npm install -g typings
rm -rf typings
typings install
```
